'use client';

import {
  Hamburger,
  Car,
  GameController,
  Pill,
  House,
  Books,
  Package,
  Briefcase,
  Rocket,
  TrendUp,
  TrendDown,
  Gift,
  Receipt,
  Sparkle,
  Hourglass,
  Warning,
  MagnifyingGlass,
  Lightbulb,
  ChartPieSlice,
  PawPrint,
  Dog,
  Cat,
  ShoppingBag,
  ShoppingCart,
  Bus,
  Train,
  AirplaneTakeoff,
  Coffee,
  Pizza,
  Bank,
  Barcode,
  CreditCard,
  Heart,
  Wallet,
  Tag,
  CurrencyDollar,
  Money,
  ChartBar,
  Target,
  Bell,
  NotePencil,
  CheckCircle,
  XCircle,
  Star,
  FilmStrip,
  Wrench,
  Baby,
  Drop,
  FirstAid,
  Tooth,
  HandTap,
  CaretLeft,
  ChatText,
  type IconProps,
} from '@phosphor-icons/react';

const iconMap: Record<string, React.ComponentType<IconProps>> = {
  Hamburger,
  Car,
  GameController,
  Pill,
  House,
  Books,
  Package,
  Briefcase,
  Rocket,
  TrendUp,
  TrendDown,
  Gift,
  Receipt,
  Sparkle,
  Hourglass,
  Warning,
  MagnifyingGlass,
  Lightbulb,
  ChartPieSlice,
  PawPrint,
  Dog,
  Cat,
  ShoppingBag,
  ShoppingCart,
  Bus,
  Train,
  AirplaneTakeoff,
  Coffee,
  Pizza,
  Bank,
  Barcode,
  CreditCard,
  Heart,
  Wallet,
  Tag,
  CurrencyDollar,
  Money,
  ChartBar,
  Target,
  Bell,
  NotePencil,
  CheckCircle,
  XCircle,
  Star,
  FilmStrip,
  Wrench,
  Baby,
  Drop,
  FirstAid,
  Tooth,
  HandTap,
  CaretLeft,
  ChatText,
};

const emojiToIcon: Record<string, string> = {
  '🍔': 'Hamburger',
  '🚗': 'Car',
  '🎮': 'GameController',
  '💊': 'Pill',
  '🏠': 'House',
  '📚': 'Books',
  '📦': 'Package',
  '⚠️': 'Warning',
  '💡': 'Lightbulb',
  '🏷️': 'Tag',
  '💰': 'CurrencyDollar',
  '📊': 'ChartBar',
  '🎯': 'Target',
  '🔔': 'Bell',
  '📝': 'NotePencil',
  '✅': 'CheckCircle',
  '❌': 'XCircle',
  '⭐': 'Star',
  '🐾': 'PawPrint',
  '🐶': 'Dog',
  '🐱': 'Cat',
  '🛍️': 'ShoppingBag',
  '🛒': 'ShoppingCart',
  '🚌': 'Bus',
  '🚆': 'Train',
  '✈️': 'AirplaneTakeoff',
  '☕': 'Coffee',
  '🍕': 'Pizza',
  '🏦': 'Bank',
  '💳': 'CreditCard',
  '❤️': 'Heart',
  '👶': 'Baby',
  '🦷': 'Tooth',
  '💧': 'Drop',
  '🎬': 'FilmStrip',
  '🔧': 'Wrench',
};

/** Lista pública de ícones disponíveis — usada pelos seletores (onboarding etc.). */
export const AVAILABLE_ICONS = Object.keys(iconMap);

function normalizeIcon(name: string): string {
  return emojiToIcon[name] ?? name;
}

interface IconRendererProps {
  name: string;
  size?: number;
  weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
  className?: string;
  color?: string;
}

export default function Icon({ name, size = 20, weight = 'regular', className, color }: IconRendererProps) {
  const iconName = normalizeIcon(name);
  const Component = iconMap[iconName];
  if (!Component) return <span className={className}>{iconName}</span>;
  return <Component size={size} weight={weight} className={className} color={color} />;
}
